### ISSUE TITLE
update password_reset_form template

### ISSUE THREAD

**Issue by yanabar** [marizoldi/Erehwon#106]
update https://github.com/marizoldi/Erehwon/blob/master/erehwon/erehwon/templates/registration/password_reset_form.html to match wireframes https://projects.invisionapp.com/share/S38QV1RCE#/screens/218105763

**Comment by binaryarun** [comment]
Hi, 
Forget password Front-end Changed. Check it. Email label name can be change in django forms
![screenshot from 2017-09-29 21-10-30](https://user-images.githubusercontent.com/12461220/31023871-dfb411f8-a55a-11e7-88c7-bf030b95ec3c.png)
