### ISSUE TITLE
Login with email only instead of password

### ISSUE THREAD

**Issue by marizoldi** [marizoldi/Erehwon#53]

**Comment by lili2311** [comment]
This will require a custom authentication written in Django to not only not use the django default user model but to also bypass the password, anyone can guess the password and simply be logged in. Is there no requirement to keep the user's projects and data safe and protected with a password?

Is email + password combo is OK this code can be re-used from Pimp where this has now been completed to allow users to sign-up and login with the email but also a password.

**Comment by marizoldi** [comment]
agreed. We can drop passwords later.
