### ISSUE TITLE
Update wireframes

### ISSUE THREAD

**Issue by marizoldi** [marizoldi/Erehwon#55]

**Comment by shraddhag2** [comment]
Thanks Mariza. I have reviewed you document and will provide my input this weekend.

**Comment by marizoldi** [comment]
Great, thanks! I am also keen to develop the site as a progressive app if we can. Have you ever made one?  : https://mobile.angular.io/

**Comment by shraddhag2** [comment]
Hello Mariza, 
I attended training on Postgres and downloaded it on my laptop. Looked at your document and thought of the database structure. I need to know the relationship between the entities such as Project, Idea etc. Can we have a chat sometime this week and come up with stories so we can develop the application in agile way as you mentioned. I have not worked on Mobile angular yet but can try if required.
Thanks,
Shraddha

**Comment by Karsco** [comment]
Hello Shraddha/Mariza

I have committed a change to the README.md with some guidance on installing Python and virtualenv/virtualenvwrapper on Windows 7.  Are you able to add some instructions on installing Postgres on Windows 7?  I have not successfully installed it yet and if you have done it and can give some guidance that would be fantastic.

Mariza, I have used AngularJS before and have heard about progressive apps.  I would be keen to have a go and would love to pair programme. Would one of you be interested in this?

I have got as far as step 9 in the README instructions.   Once I have managed to set the project up I would love to contribute some frontend functionality.

Thanks and hope the addition to the README is OK as a start.
Karen.

**Comment by marizoldi** [comment]
Hello Karen

Great! Shraddgha is your person for AngularJS =)

Can you raise a PR for README updates? Also, let's move this thread discussion on Slack.

**Comment by Karsco** [comment]
Hi Mariza

I can raise a PR if you can just let new know what this is.  Sorry, I am a
bit new to this.

Thanks
Karen

**Comment by Karsco** [comment]
Hi Shraddha

Are you interested in pair programming with me?  If so, how might it work
best?  We could meet up once a week for a couple of hours or maybe we could
do it remotely?

Look forward to hearing from you.
Best wishes
Karen

**Comment by shraddhag2** [comment]
Hello Ladies,

I intalled Postgress by watching this video :
https://app.pluralsight.com/library/courses/postgresql-getting-started/table-of-contents
I could install the database successfully.

Karsco, I live in Staines and work fulltime as Dot Net web developer. I
cannot visit London often but we can chat on Skype when required.
I have learned Angular recently I will try to  give my best here :-)

I have some experience of mobile-first development approach. The below link
is good for basic understanding.
https://codelabs.developers.google.com/codelabs/your-first-pwapp/#0

All, can we create some stories/PBIs or tickets to start with this app?

Mariza, can you tell me the relationship between the Project, Idea and call
for actions please? this will help to start to design the database.

Thanks,
Shraddha

**Comment by marizoldi** [comment]
Hi Shraddha,

I have replied to you on Slack. This is a closed comment and we should move the discussion over at Slack.
